# Generated by Django 2.2.5 on 2021-06-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=240, null=True)),
                ('standard', models.IntegerField(blank=True, max_length=240, null=True)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('student', models.CharField(blank=True, max_length=240, null=True)),
                ('term', models.IntegerField(blank=True, max_length=240, null=True)),
                ('mark', models.IntegerField(blank=True, max_length=240, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, max_length=240, null=True)),
            ],
        ),
    ]
