# Generated by Django 2.2.5 on 2021-04-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institute_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='lastname',
        ),
    ]
