# Generated by Django 2.2.5 on 2021-04-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_auto_20210406_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedusers',
            old_name='insitituite',
            new_name='instituite',
        ),
    ]
