# Generated by Django 2.2.5 on 2021-04-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0006_auto_20210406_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedusers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
