# Generated by Django 2.2.5 on 2021-04-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0009_institute_is_verfilfied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='is_verfilfied',
            new_name='is_verified',
        ),
    ]
