# Generated by Django 2.2.5 on 2021-06-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0011_auto_20210604_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateTimeField(auto_now=True)),
                ('instituite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.Institute')),
            ],
        ),
    ]
