# Generated by Django 3.1.4 on 2021-01-11 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=125, null=True)),
                ('street', models.CharField(blank=True, max_length=125, null=True)),
                ('state', models.CharField(blank=True, choices=[('01', 'Jammu and Kashmir'), ('02', 'Himachal Pradesh'), ('03', 'Punjab'), ('04', 'Chattisgarh'), ('05', 'UTTARAKHAND'), ('06', 'Haryana'), ('07', 'DELHI'), ('08', 'Rajasthan'), ('09', 'Uttar Pradesh'), ('10', 'Bihar'), ('11', 'Sikkim'), ('12', 'Arunachal Pradesh'), ('13', 'Nagaland'), ('14', 'Manipur'), ('15', 'MIZORAM'), ('16', 'TRIPURA'), ('17', 'Megalaya'), ('18', 'Assam'), ('19', 'West Bengal'), ('20', 'Jharkhand'), ('21', 'ODISHA'), ('22', 'CHATTISGARH'), ('23', 'Madhya Pradesh'), ('24', 'Gujarat'), ('25', 'DAMAN AND DIU'), ('26', 'DADRA AND NAGAR HAVELI'), ('27', 'Maharashtra'), ('38', 'ANDHRA PRADESH (BEFORE DIVISION)'), ('29', 'Karnataka'), ('30', 'Goa'), ('31', 'LAKSHADWEEP'), ('32', 'Kerala'), ('33', 'Tamil Nadu'), ('34', 'PUDUCHERRY'), ('35', 'ANDAMAN AND NICOBAR ISLANDS'), ('36', 'TELANGANA'), ('37', 'ANDHRA PRADESH (NEW)')], max_length=125, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=125, null=True)),
                ('landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, choices=[('91', 'India')], default='91', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('user_uid', models.CharField(blank=True, max_length=250, null=True)),
                ('registered_from', models.CharField(blank=True, choices=[('web_app', 'Customer Web App'), ('admin_portal', 'Admin Portal')], default='web_app', max_length=125, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('acc_status', models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted'), ('S', 'Suspended')], max_length=125, null=True)),
                ('profile_status', models.CharField(blank=True, choices=[('A', 'Active'), ('AV', 'Awaiting Account Verification'), ('APV', 'Awaiting Phone Number Verification'), ('AEV', 'Awaiting Email Verification')], max_length=125, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=125, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('sms_alert', models.BooleanField(default=False)),
                ('email_alert', models.BooleanField(default=False)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('address_added', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.contactaddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-member_since',),
            },
        ),
    ]
