# Generated by Django 3.1.4 on 2021-02-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_pic1',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_pic2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
