# Generated by Django 3.1.4 on 2021-02-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_remove_customerprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_pic3',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
