# Generated by Django 2.2.5 on 2021-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_customerprofile_profile_pic3'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
