# Generated by Django 2.2.5 on 2021-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='covid_status',
            field=models.CharField(blank=True, choices=[('N', 'Negative'), ('P', 'Positive'), ('V', 'Verification')], default='N', max_length=125, null=True),
        ),
    ]
