# Generated by Django 2.2.5 on 2021-06-06 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_customerprofile_covid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPositivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_status', models.CharField(blank=True, choices=[('N', 'Negative'), ('P', 'Positive'), ('V', 'Verification')], default='N', max_length=125, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postivity_logs', to='usermanagement.CustomerProfile')),
            ],
        ),
    ]
