# Generated by Django 2.2.5 on 2021-06-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_userpositivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpositivitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to='usermanagement.CustomerProfile'),
        ),
    ]
